version: "3.8"

networks:
  npm-network:
    driver: bridge

services:

  # NGINX Proxy Manager
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: always
    ports:
      - "9080:80"       # HTTP
      - "9443:443"      # HTTPS
      - "9081:81"       # Admin UI
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    networks:
      - npm-network

  # Laravel App
  laravel-app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: app-laravel
    restart: always
    expose:
      - "9000"  # PHP-FPM port
    env_file:
      - .env
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - npm-network

  mysql:
    image: mysql:8
    container_name: mysql-laravel
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - npm-network

  redis:
    image: redis:alpine
    container_name: redis-laravel
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - npm-network

volumes:
  mysql_data:
  redis_data:
